services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SqlServer2024!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - loja_network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "SqlServer2024!" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: loja_db_init
    volumes:
      - ./Setup.sql:/tmp/Setup.sql
    networks:
      - loja_network
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      /bin/bash -c "
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P 'SqlServer2024!' -C -i /tmp/Setup.sql
      "
    restart: "no"

  app:
    build:
      context: ./SistemaLoja
      dockerfile: Dockerfile
    container_name: sistema_loja_app
    environment:
      - SQL_SERVER=sqlserver
    depends_on:
      db-init:
        condition: service_completed_successfully
    networks:
      - loja_network
    stdin_open: true
    tty: true

volumes:
  sqlserver_data:

networks:
  loja_network:
    driver: bridge
